config:
  credentials: []
  project_repos: {}
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Doc:
    repos:
      this_repo:
        commands:
        - npm run docs
        container: processing
  QC.Sty:
    repos:
      this_repo:
        commands:
        - npm ci --audit=false && ./node_modules/.bin/eslint ./ -f checkstyle -o eslint-codestyle.xml
        container: processing
  QC.Uni:
    repos:
      this_repo:
        commands:
        - npm run test -- --coverage --watchAll=false .
        container: processing
timeout: 600
